# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: pravallikaseshasai@gmail.com
author_name: Nunna Pravallika Sesha Sai
contract_name: counter_local_state
deployment_language: python
preset_name: starter
project_name: counter_local_state

